export enum TYPES_PROGRAM {
    FORMAL = 'FORMAL',
    INFORMAL = 'INFORMAL'
}

export enum SUB_TYPES_PROGRAM {
    DIPLOMATE = 'DIPLOMATE',
    MASTERCLASS = 'MASTERCLASS',
    MASTER = 'MASTER',
    PhD = 'PhD'
}

export enum TYPES_MODALITY {
    PRESENCIAL = 'PRESENCIAL',
    SEMI_PRESENCIAL = 'SEMI_PRESENCIAL',
    VIRTUAL = 'VIRTUAL',
}
